urls.py
from django.conf.urls.defaults import patterns, include, url
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from ebooks import views
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', views.overview),
    url(r'show/(?P<type>\w+)/(?P<dataid>\d+)/', views.show_data ),

    url(r'studip', views.studip_json_data),

    url(r'manage/ebooks/$', views.manage_ebooks ),
    url(r'manage/ebooks/move/$', views.submit_ebook_move ),
    url(r'manage/ebooks/add/$', views.add_ebook),

    url(r'search/$', views.search_items),

    url(r'manage/user/profile/$', views.manage_user_profile),
    url(r'login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'} ),
    url(r'logout/$', 'django.contrib.auth.views.logout_then_login' ),

    url(r'^favicon\.ico$', 'django.views.generic.simple.redirect_to', {'url': '/static/img/favicon.ico'}),
    # admin
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

ebooks/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import os


class Directory(models.Model):
    name = models.CharField(max_length=100)
    dirname = models.CharField(max_length=100)
    parent = models.ForeignKey('Directory', null=True)
    description = models.CharField(max_length=100, blank=True)
    serial = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_relative_path(self):
        path = ""
        for d in self.get_relative_path_components():
            path = os.path.join(path, d.dirname)
        return path

    def get_relative_path_components(self):
        components = []
        c = self
        while c is not None:
            components.insert(0, c)
            c = c.parent
        return components

    def has_ebooks(self):
        try:
            Ebook.objects.get(directory=self)
        except Exception:
            return False
        return True

    def get_ebooks(self):
        ebooks = []
        try:
            for ebook in Ebook.objects.order_by('name').filter(directory=self):
                ebooks.append(ebook)
        except Exception:
            pass
        return ebooks

    def get_directories(self):
        dirs = []
        try:
            for d in Directory.objects.order_by('name').filter(parent=self):
                dirs.append(d)
        except Exception:
            pass
        return dirs


class Ebook(models.Model):
    name = models.CharField(max_length=100)
    size = models.IntegerField()
    filename = models.CharField(max_length=100)
    icon = models.CharField(max_length=10)
    directory = models.ForeignKey('Directory')
    hashvalue = models.CharField(max_length=100)
    hasThumbnail = models.BooleanField()
    serial = models.IntegerField()
    indexed = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name

    def get_relative_path(self):
        return os.path.join(self.directory.get_relative_path(),
                            self.filename)


class UserProfile(models.Model):
    """
        Model, welches zusätzliche Informationen über einen
        Nutzer speichert
    """
    user = models.OneToOneField(User)
    hasKindle = models.BooleanField()
    KindleAddress = models.EmailField()


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)


class EbookInformation(object):
    def __init__(self, ebook, form):
        self.ebook = ebook
        self.filepath = self.__generate_path(ebook)
        self.form = form

    def __generate_path(self, ebook):
        return ebook.get_relative_path()

ebooks/forms.py
# -*- coding: utf-8 -*-
from django.forms import ModelForm, Form
from ebooks.models import Ebook
from django import forms
import settings


class EbookForm(ModelForm):
    class Meta:
        model = Ebook


class EbookUploadForm(Form):
    file = forms.FileField()


class EbookManagementForm(Form):
    selected = forms.BooleanField()


class EbookActionSelectForm(Form):
    action = forms.ChoiceField(choices=settings.CHOICES_FOR_EBOOKS)


class EbookMovementForm(ModelForm):
    class Meta:
        model = Ebook
        fields = ('name', 'directory')

templates/base.html
<!DOCTYPE html>
{% load static %}
{% get_static_prefix as STATIC_URL %}
{% get_media_prefix as MEDIA_URL %}
<html>
<head>
	<title>{% block title %}Startseite{% endblock title %} - eBook-Management</title>

	<meta http-equiv="content-type" content="text/html;charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/overrides.css" />
    <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/bootstrap-responsive.min.css" />

    <script src="{{ STATIC_URL }}js/jquery-1.7.1.min.js"></script>
    <script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>

    {% block meta %}{% endblock meta %}
</head>

<body>

<!-- navigation bar on top -->
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <a class="brand" href="/">ebooks.i77i.de</a>

      {% if user.is_authenticated %}

      <div class="nav-collapse">
        <ul class="nav">
          <li><a href="/manage/ebooks/add/">Ebooks hinzufügen</a></li>
        </ul>


        <ul class="nav">
          <li class="dropdown">
          <a href="#" class="dropdown-toggle"
            data-toggle="dropdown">Hallo {{ user.first_name }} {{ user.last_name }}<b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><a href="/manage/user/profile/">Benutzereinstellungen</a></li>
            <li><a href="/logout">Logout</a></li>
          </ul>
          </li>
        </ul>


        <form method="get" action="/search/" class="navbar-search pull-right">
            <input type="text" name="query"
              class="search-query" placeholder="Suchen"/>
        </form>

      </div>

      {% endif %}

    </div>
  </div>
</div>

<div class="container">

  <div class="row">
    <div class="span12">
      {% block content %}{% endblock %}
    </div>
  </div>

  <hr />
  <div class="row">
    <div class="span12">
      &copy; {% now "Y" %} Philipp Böhm - powered by
      <a href="https://www.djangoproject.com/">Django</a>
    </div>
  </div>
</div>
</body>

</html>

templates/directory_listing.html
{% extends "base.html" %}
{% block title %}Übersicht der Kategorien{% endblock %}

{% block content %}
{% include "shared/breadcrumbs.html" %}
<h2 id="site_description">Verzeichnisinhalt von "{{ current_directory.name }}"</h2>
{% include "shared/directories.html" %}
{% include "shared/ebooks.html" %}
{% endblock %}

templates/ebook_upload.html
{% extends "base.html" %}

{% block title %} Ebooks hinzufügen {% endblock title %}

{% block content %}

<div class="page-header">
  <h2>Ebooks hinzufügen</h2>
</div>

<div class="well">
  <form method="post" action="/manage/ebooks/add/"
      enctype="multipart/form-data">
  <table>
      {{ upload_form.as_table }}
  </table>

  <input type="submit" class="btn btn-primary" value="Hinzufügen" />
  </form>
</div>

{% endblock %}

templates/item_list.html
{% extends "base.html" %}
{% block title %}{{ sitetitle }}{% endblock %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/item_list.css" />
<script src="{{ STATIC_URL }}js/jquery-1.7.1.min.js"></script>
{% endblock %}
    
{% block content %}

{% if dir_count > 0 %}
<div id="directory_overview">
    <strong>Verzeichnisse</strong>

    <table class="list">
        {% for dir in directories %}
        <tr {% cycle 'class="highlighted"' '' %}>
            <td class="foldericon">
                <img src="{{ STATIC_URL }}fileicons/folder.png"/>
            </td>

            <td>
                <a class="directory" href="/show/directory/{{ dir.id }}">{{dir.name}}</a>
            </td>
        </tr>
        {% endfor %}
    </table>

</div>
{% endif %}


{% if ebook_count > 0 %}
<div id="ebook_overview">
    <strong>Ebooks</strong>
    <form method="post" action="/manage/ebooks/">
    <table class="list">
        {% for eb in ebooks %}
            <tr {% cycle 'class="highlighted"' '' %}>
                <td class="fileicon">
                    <a{% if eb.ebook.hasThumbnail %}
                        class="thumbnail" href="{{ MEDIA_URL }}.thumbnails/{{ eb.ebook.hashvalue }}.png"
                        {% endif %} title="{{ eb.ebook.filename }}">
                        <img src="{{ STATIC_URL }}fileicons/{{ eb.ebook.icon }}.png"/>
                    </a>    
                </td>
                <td class="filename">
                    <a href="{{ MEDIA_URL }}{{ eb.filepath|urlencode }}">{{eb.ebook.filename}}</a>
                </td>
                <td class="filesize">
                    <span>{{ eb.ebook.size|filesizeformat}}</span>
                </td>
                <td class="fileselected">
                    {{ eb.form.selected }}
                </td>
            </tr>
        {% endfor %}
        <tr class="lastrow">
            <td colspan="4">
                {{ action.action }}
                <input id="submit_action" type="submit" value="Aktionen durchführen"/>
            </td>
        </tr>
    </table>
    </form>
</div>
{% endif %}

<script>
this.imagePreview = function(){	
	/* CONFIG */
		
		xOffset = 70;
		yOffset = 20;
		
		// these 2 variable determine popup's distance from the cursor
		// you might want to adjust to get the right result
		
	/* END CONFIG */
	$("a.thumbnail").hover(function(e){
		this.t = this.title;
		$("#container").append("<p id='preview'><img src='"+ this.href +"' alt='Image preview' /></p>");								 
		$("#preview")
			.css("top",(e.pageY - xOffset) + "px")
			.css("left",(e.pageX + yOffset) + "px")
			.fadeIn("fast");						
    },
	function(){
		this.title = this.t;	
		$("#preview").remove();
    });	
	$("a.thumbnail").mousemove(function(e){
		$("#preview")
			.css("top",(e.pageY - xOffset) + "px")
			.css("left",(e.pageX + yOffset) + "px");
	});			
};


// starting the script on page load
$(document).ready(function(){
	imagePreview();
});

//
// Submit Button entfernen, wenn Javascript aktiv ist
//
$(document).ready(function(){
    $('#submit_action').css("display", "none");
    $('#id_action').change(function() {
        $(this).closest("form").submit();
    });
});

</script>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% load url from future %}

{% block title %} Login {% endblock title %}

{% block content %}
<div class="row">
  <div class="span12">

    <div class="hero-unit">
      <h1>Willkommen</h1>
      <p></p>
      <p>auf <a href="#">ebooks.i77i.de</a>, der Ebook-Management Platform
      für den belesenen Studenten.</p>
    </div>

  </div>
</div>

<div class="row">
  <div class="span5">

    <div class="page-header">
      <h1>Login</h1>
    </div>

    {% if form.errors %}
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">×</a>
      Nutzername oder Passwort sind nicht korrekt!
    </div>
    {% endif %}

    <form class="well" method="post" action="{% url 'django.contrib.auth.views.login' %}">
    {% csrf_token %}

    <fieldset>
      {{ form.username.label_tag }}
      {{ form.username }}
      {{ form.password.label_tag }}
      {{ form.password }}
    </fieldset>

    <input type="submit" class="btn btn-primary" value="Einloggen" />
    <input type="hidden" name="next" value="{{ next }}" />
    </form>

  </div>
  <div class="span7"></div>
</div>

{% endblock %}

templates/move_ebooks.html
{% extends "base.html" %}
{% block title %}Ebooks verschieben{% endblock %}

{% block meta %}
<link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/move_ebooks.css" />
{% endblock %}
    
{% block content %}
<h3>Verschieben von Ebooks</h3>
<div id="ebook_forms">
    <form method="post" action="/manage/ebooks/move/" >
        {% for form in forms %}
        <table>
            {{ form.as_table }}
        </table>
        <br/>
        {% endfor %}
        <input type="submit" value="Ebooks in die neuen Gruppen einordnen"/>
    </form>
</div>
{% endblock %}

templates/overview.html
{% extends "base.html" %}
{% block title %}Übersicht der Kategorien{% endblock %}

{% block content %}
{% include "shared/breadcrumbs.html" %}
<h2 id="site_description">Vorhandene Ebook-Kategorien</h2>
{% include "shared/directories.html" %}
{% include "shared/recent_ebooks.html" %}

{% endblock %}

templates/search_results.html
{% extends "base.html" %}
{% block title %}Übersicht der Kategorien{% endblock %}

{% block content %}
<h2>Suchergebnisse für "{{ search_query }}"</h2>

{% include "shared/ebooks.html" %}
{% endblock %}

templates/shared/breadcrumbs.html
<ul class="breadcrumb">

  <li>
    <a href="/">Startseite</a>
    <span class="divider">/</span>
  </li>

  {% for c in current_directory.get_relative_path_components %}
    <li>
      <a href="/show/directory/{{ c.id }}">{{ c.name }}</a>
      <span class="divider">/</span>
    </li>
  {% endfor %}

</ul>

templates/shared/directories.html
<div id="directory_overview">
    <table class="table table-striped ">
        {% for dir in directories %}
            <tr>
                <!-- <td class="foldericon"> -->
                <!--     <img src="{{ STATIC_URL }}fileicons/folder.png"/> -->
                <!-- </td> -->
                <td class="foldername">
                    <a class="directory" href="/show/directory/{{ dir.id }}">{{dir.name}}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>

templates/shared/ebooks.html
<div id="ebook_overview">
    <form method="post" action="/manage/ebooks/">

    <table class="table table-striped">
        {% for eb in ebooks %}
            <tr {% cycle 'class="highlighted"' '' %}>
                <!-- <td class="fileicon"> -->
                <!--     <a{% if eb.ebook.hasThumbnail %} -->
                <!--         class="thumbnail" href="{{ MEDIA_URL }}.thumbnails/{{ eb.ebook.hashvalue }}.png" -->
                <!--         {% endif %} title="{{ eb.ebook.filename }}"> -->
                <!--         <img src="{{ STATIC_URL }}fileicons/{{ eb.ebook.icon }}.png"/> -->
                <!--     </a> -->
                <!-- </td> -->
                <td class="filename">
                    <a href="{{ MEDIA_URL }}{{ eb.filepath|urlencode }}">{{eb.ebook.filename}}</a>
                </td>
                <td class="filesize">
                    <span>{{ eb.ebook.size|filesizeformat}}</span>
                </td>
                <td class="fileselected">
                    {{ eb.form.selected }}
                </td>
            </tr>
        {% endfor %}
        <tr class="lastrow">
            <td colspan="4">
                {{ action.action }}
                <input id="submit_action" type="submit" value="Aktionen durchführen"/>
            </td>
        </tr>
    </table>
    </form>
</div>

<script>
this.imagePreview = function(){

    xOffset = 70;
    yOffset = 20;

	$("a.thumbnail").hover(function(e){
		this.t = this.title;
		$("#container").append("<p id='preview'><img src='"+ this.href +"' alt='Image preview' /></p>");
		$("#preview")
			.css("top",(e.pageY - xOffset) + "px")
			.css("left",(e.pageX + yOffset) + "px")
			.fadeIn("fast");
    },
	function(){
		this.title = this.t;
		$("#preview").remove();
    });

    $("a.thumbnail").mousemove(function(e){
		$("#preview")
			.css("top",(e.pageY - xOffset) + "px")
			.css("left",(e.pageX + yOffset) + "px");
	});
};

$(document).ready(function(){
	imagePreview();
});

// Submit Button entfernen, wenn Javascript aktiv ist
$(document).ready(function(){
    $('#submit_action').css("display", "none");
    $('#id_action').change(function() {
        $(this).closest("form").submit();
    });
});
</script>

templates/shared/recent_ebooks.html
<div id="recent_ebooks">
    <h2>Aktuellste Ebooks</h2>
    <table class="table table-condensed table-striped">
        {% for eb in recent_ebooks %}
            <tr {% cycle 'class="highlighted"' '' %}>
                <td class="ebookname">
                    <a href="{{ MEDIA_URL }}{{ eb.get_relative_path|urlencode }}">{{eb.filename}}</a>
                </td>
                <td class="indexdate">
                    {{eb.indexed|date:"SHORT_DATETIME_FORMAT"}}
                </td>
                <td class="directory">
                    <a href="/show/directory/{{ eb.directory.id }}/">{{ eb.directory.dirname}}</a>
                </td>
            </tr>
        {% endfor %}
    </table>
</div>